apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31327
      name: http
    - port: 443
      targetPort: 443
      nodePort: 31913
      name: https
  type: NodePort
  
